# Generated by Django 5.2.6 on 2025-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Taom nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi?')),
            ],
        ),
    ]
