# Generated by Django 5.2.6 on 2025-09-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_category_product_delete_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
