# Generated by Django 5.2.6 on 2025-10-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
